name: teste

on: [push]

jobs:
        build:
    
                runs-on: ubuntu-latest
                strategy:
                        matrix:
                                compiler: [gcc]
                steps:
                        - uses: actions/checkout@v2
                        - name: afisare Nume
                          run: echo "Florian Silviu"
                        - name: executabil
                          run: make program
                        - name: verificare program
                          run: ls -l program*
                        - name: test1
                          run: if[ $("./program 1 2") = 5 ]; then exit(1); fi
                        - name: test2
                          run: ./program 1000000 99999999
                        - name: test3
                          run: ./program 555 -111111
                        - name: test4
                          run: ./program -234567 -5433
                        - name: test5
                          run: ./program 5225 187631
                         